config/routes.rb
Konsalt::Application.routes.draw do
  resources :correspondences

  resources :risks

  resources :staffs

  resources :correspondence_types

  resources :projects do
    resources :representatives
    resources :stakeholders
  end

  resources :representatives

  resources :stakeholders do
  end
  
  match 'stakeholders/:id/representatives' => 'stakeholders#representatives'

  root :to => 'application#index'

end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base
  has_many :representatives
  has_and_belongs_to_many :projects
end

app/controllers/stakeholders_controller.rb
class StakeholdersController < ApplicationController
  # GET /stakeholders
  # GET /stakeholders.json
  def index
    @stakeholders = Stakeholder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stakeholders }
    end
  end

  # GET /stakeholders/1
  # GET /stakeholders/1.json
  def show
    @stakeholder = Stakeholder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stakeholder }
    end
  end

  # GET /stakeholders/new
  # GET /stakeholders/new.json
  def new
    @stakeholder = Stakeholder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stakeholder }
    end
  end

  # GET /stakeholders/1/edit
  def edit
    @stakeholder = Stakeholder.find(params[:id])
  end
  
  # GET /stakeholders/1/representatives
  def representatives
    @representatives = Stakeholder.find(params[:id]).representatives

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @representatives }
    end
  end

  # POST /stakeholders
  # POST /stakeholders.json
  def create
    @stakeholder = Stakeholder.new(params[:stakeholder])

    respond_to do |format|
      if @stakeholder.save
        format.html { redirect_to @stakeholder, notice: 'Stakeholder was successfully created.' }
        format.json { render json: @stakeholder, status: :created, location: @stakeholder }
      else
        format.html { render action: "new" }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stakeholders/1
  # PUT /stakeholders/1.json
  def update
    @stakeholder = Stakeholder.find(params[:id])

    respond_to do |format|
      if @stakeholder.update_attributes(params[:stakeholder])
        format.html { redirect_to @stakeholder, notice: 'Stakeholder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stakeholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stakeholders/1
  # DELETE /stakeholders/1.json
  def destroy
    @stakeholder = Stakeholder.find(params[:id])
    @stakeholder.destroy

    respond_to do |format|
      format.html { redirect_to stakeholders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stakeholders_helper.rb
module StakeholdersHelper
end

app/views/stakeholders/_form.html.erb
<%= form_for(@stakeholder) do |f| %>
  <% if @stakeholder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stakeholder.errors.count, "error") %> prohibited this stakeholder from being saved:</h2>

      <ul>
      <% @stakeholder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organisation %><br />
    <%= f.text_field :organisation %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :address3 %><br />
    <%= f.text_field :address3 %>
  </div>
  <div class="field">
    <%= f.label :suburb %><br />
    <%= f.text_field :suburb %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :post_address1 %><br />
    <%= f.text_field :post_address1 %>
  </div>
  <div class="field">
    <%= f.label :post_address2 %><br />
    <%= f.text_field :post_address2 %>
  </div>
  <div class="field">
    <%= f.label :post_address3 %><br />
    <%= f.text_field :post_address3 %>
  </div>
  <div class="field">
    <%= f.label :post_suburb %><br />
    <%= f.text_field :post_suburb %>
  </div>
  <div class="field">
    <%= f.label :post_state %><br />
    <%= f.text_field :post_state %>
  </div>
  <div class="field">
    <%= f.label :post_postcode %><br />
    <%= f.text_field :post_postcode %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stakeholders/edit.html.erb
<h1>Editing stakeholder</h1>

<%= render 'form' %>

<%= link_to 'Show', @stakeholder %> |
<%= link_to 'Back', stakeholders_path %>

app/views/stakeholders/index.html.erb
<h1>Listing stakeholders</h1>

<table>
  <tr>
    <th>Organisation</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>Address3</th>
    <th>Suburb</th>
    <th>State</th>
    <th>Postcode</th>
    <th>Post address1</th>
    <th>Post address2</th>
    <th>Post address3</th>
    <th>Post suburb</th>
    <th>Post state</th>
    <th>Post postcode</th>
    <th>Phone1</th>
    <th>Phone2</th>
    <th>Fax</th>
    <th>Email</th>
    <th>Website</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stakeholders.each do |stakeholder| %>
  <tr>
    <td><%= stakeholder.organisation %></td>
    <td><%= stakeholder.address1 %></td>
    <td><%= stakeholder.address2 %></td>
    <td><%= stakeholder.address3 %></td>
    <td><%= stakeholder.suburb %></td>
    <td><%= stakeholder.state %></td>
    <td><%= stakeholder.postcode %></td>
    <td><%= stakeholder.post_address1 %></td>
    <td><%= stakeholder.post_address2 %></td>
    <td><%= stakeholder.post_address3 %></td>
    <td><%= stakeholder.post_suburb %></td>
    <td><%= stakeholder.post_state %></td>
    <td><%= stakeholder.post_postcode %></td>
    <td><%= stakeholder.phone1 %></td>
    <td><%= stakeholder.phone2 %></td>
    <td><%= stakeholder.fax %></td>
    <td><%= stakeholder.email %></td>
    <td><%= stakeholder.website %></td>
    <td><%= stakeholder.notes %></td>
    <td><%= link_to 'Show', stakeholder %></td>
    <td><%= link_to 'Edit', edit_stakeholder_path(stakeholder) %></td>
    <td><%= link_to 'Destroy', stakeholder, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stakeholder', new_stakeholder_path %>

app/views/stakeholders/new.html.erb
<h1>New stakeholder</h1>

<%= render 'form' %>

<%= link_to 'Back', stakeholders_path %>

app/views/stakeholders/representatives.html.erb
<h1>Listing representatives</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Surname</th>
    <th>Stakeholder</th>
    <th>Mobile</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @representatives.each do |representative| %>
  <tr>
    <td><%= representative.first_name %></td>
    <td><%= representative.surname %></td>
    <td><%= link_to representative.stakeholder.organisation,representative.stakeholder %></td>
    <td><%= link_to representative.mobile, "tel:#{ representative.mobile.gsub(/\s+/, "") }" %></td>
    <td><%= representative.notes %></td>
    <td><%= link_to 'Show', representative %></td>
    <td><%= link_to 'Edit', edit_representative_path(representative) %></td>
    <td><%= link_to 'Destroy', representative, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Representative', new_representative_path %>

app/views/stakeholders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Organisation:</b>
  <%= @stakeholder.organisation %>
</p>

<p>
  <b>Address1:</b>
  <%= @stakeholder.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @stakeholder.address2 %>
</p>

<p>
  <b>Address3:</b>
  <%= @stakeholder.address3 %>
</p>

<p>
  <b>Suburb:</b>
  <%= @stakeholder.suburb %>
</p>

<p>
  <b>State:</b>
  <%= @stakeholder.state %>
</p>

<p>
  <b>Postcode:</b>
  <%= @stakeholder.postcode %>
</p>

<p>
  <b>Post address1:</b>
  <%= @stakeholder.post_address1 %>
</p>

<p>
  <b>Post address2:</b>
  <%= @stakeholder.post_address2 %>
</p>

<p>
  <b>Post address3:</b>
  <%= @stakeholder.post_address3 %>
</p>

<p>
  <b>Post suburb:</b>
  <%= @stakeholder.post_suburb %>
</p>

<p>
  <b>Post state:</b>
  <%= @stakeholder.post_state %>
</p>

<p>
  <b>Post postcode:</b>
  <%= @stakeholder.post_postcode %>
</p>

<p>
  <b>Phone1:</b>
  <%= @stakeholder.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @stakeholder.phone2 %>
</p>

<p>
  <b>Fax:</b>
  <%= @stakeholder.fax %>
</p>

<p>
  <b>Email:</b>
  <%= @stakeholder.email %>
</p>

<p>
  <b>Website:</b>
  <%= @stakeholder.website %>
</p>

<p>
  <b>Notes:</b>
  <%= @stakeholder.notes %>
</p>


<%= link_to 'Edit', edit_stakeholder_path(@stakeholder) %> |
<%= link_to 'Back', stakeholders_path %>