config/routes.rb
Konsalt::Application.routes.draw do
  resources :correspondences

  resources :risks

  resources :staffs

  resources :correspondence_types

  resources :projects do
    resources :representatives
    resources :stakeholders
  end

  resources :representatives

  resources :stakeholders do
  end
  
  match 'stakeholders/:id/representatives' => 'stakeholders#representatives'

  root :to => 'application#index'

end

app/models/correspondence.rb
class Correspondence < ActiveRecord::Base
  belongs_to :correspondence_type
  belongs_to :representative
  belongs_to :stakeholder
  belongs_to :risk
  belongs_to :project
end

app/models/correspondence_type.rb
class CorrespondenceType < ActiveRecord::Base
end

app/controllers/correspondences_controller.rb
class CorrespondencesController < ApplicationController
  # GET /correspondences
  # GET /correspondences.json
  def index
    @correspondences = Correspondence.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @correspondences }
    end
  end

  # GET /correspondences/1
  # GET /correspondences/1.json
  def show
    @correspondence = Correspondence.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @correspondence }
    end
  end

  # GET /correspondences/new
  # GET /correspondences/new.json
  def new
    @correspondence = Correspondence.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @correspondence }
    end
  end

  # GET /correspondences/1/edit
  def edit
    @correspondence = Correspondence.find(params[:id])
  end

  # POST /correspondences
  # POST /correspondences.json
  def create
    @correspondence = Correspondence.new(params[:correspondence])

    respond_to do |format|
      if @correspondence.save
        format.html { redirect_to @correspondence, notice: 'Correspondence was successfully created.' }
        format.json { render json: @correspondence, status: :created, location: @correspondence }
      else
        format.html { render action: "new" }
        format.json { render json: @correspondence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /correspondences/1
  # PUT /correspondences/1.json
  def update
    @correspondence = Correspondence.find(params[:id])

    respond_to do |format|
      if @correspondence.update_attributes(params[:correspondence])
        format.html { redirect_to @correspondence, notice: 'Correspondence was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @correspondence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correspondences/1
  # DELETE /correspondences/1.json
  def destroy
    @correspondence = Correspondence.find(params[:id])
    @correspondence.destroy

    respond_to do |format|
      format.html { redirect_to correspondences_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/correspondences_helper.rb
module CorrespondencesHelper
end

app/views/correspondences/_form.html.erb
<%= semantic_form_for @correspondence do |f| %>
  <% if @correspondence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correspondence.errors.count, "error") %> prohibited this correspondence from being saved:</h2>

      <ul>
      <% @correspondence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.inputs :name => "Details" do %>
    <%= f.input :date_received %>
    <%= f.input :project %>
    <%= f.input :correspondence_type %>
    <%= f.input :stakeholder, :collection=>ProjectsStakeholders.where("project_id=#{@correspondence[:project_id]}").collect {|ps| [ps.stakeholder[:organisation], ps.stakeholder[:id]]} %>
    <%= f.input :representative, :collection=>Representative.where(:stakeholder_id=>@correspondence[:stakeholder_id]).collect {|r| ["#{r[:first_name]} #{r[:surname]}", r[:id]]} %>
    <%= f.input :subject %>
    <%= f.input :comment %>
    <%= f.input :risk %>
  <% end %>
  
  <%= f.actions do %>
    <%= f.action :submit, :as => :button %>
    <%= f.action :cancel, :as => :link %>
  <% end %>    
<% end %>

app/views/correspondences/edit.html.erb
<h1>Editing correspondence</h1>

<%= render 'form' %>

<%= link_to 'Show', @correspondence %> |
<%= link_to 'Back', correspondences_path %>

app/views/correspondences/index.html.erb
<h1>Listing correspondences</h1>

<table>
  <tr>
    <th>Date received</th>
    <th>Project</th>
    <th>Correspondence type</th>
    <th>Representative</th>
    <th>Stakeholder</th>
    <th>Subject</th>
    <th>Comment</th>
    <th>Risk</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @correspondences.each do |correspondence| %>
  <tr>
    <td><%= correspondence.date_received %></td>
    <td><%= correspondence.project.name %></td>
    <td><%= link_to correspondence.correspondence_type.name, correspondence.correspondence_type %></td>
    <td><%= link_to "#{correspondence.representative.first_name} #{correspondence.representative.surname}", correspondence.representative %></td>
    <td><%= link_to correspondence.stakeholder.organisation, correspondence.stakeholder %></td>
    <td><%= correspondence.subject %></td>
    <td><%= correspondence.comment %></td>
    <td><%= link_to correspondence.risk.name, correspondence.risk %></td>
    <td><%= link_to 'Show', correspondence %></td>
    <td><%= link_to 'Edit', edit_correspondence_path(correspondence) %></td>
    <td><%= link_to 'Destroy', correspondence, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Correspondence', new_correspondence_path %>

app/views/correspondences/new.html.erb
<h1>New correspondence</h1>

<%= form_for(@correspondence) do |f| %>
  <% if @correspondence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correspondence.errors.count, "error") %> prohibited this correspondence from being saved:</h2>

      <ul>
      <% @correspondence.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_received %><br />
    <%= f.datetime_select :date_received %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= collection_select :correspondence, :project_id, Project.all.collect{|p| [p[:id], "#{p[:number]}:#{p[:name]}"]}, :first, :last, {:include_blank => 'Please Select'} %>
  </div>
  <div class="field">
    <%= f.label :correspondence_type %><br />
    <%= collection_select :correspondence, :correspondence_type_id, CorrespondenceType.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :stakeholder %><br />
    <%= f.select "stakeholder_id", "stakeholder_id", { }, {:disabled=>true} %>
  </div>
  <div class="field">
    <%= f.label :representative %><br />
    <%= f.select "representative_id", "representative_id", {}, {:disabled=>true} %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :risk %><br />
    <%= collection_select :correspondence, :risk_id, Risk.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', correspondences_path %>

app/views/correspondences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date received:</b>
  <%= @correspondence.date_received %>
</p>

<p>
  <b>Project:</b>
  <%= link_to @correspondence.project.name, @correspondence.project %>
</p>

<p>
  <b>Correspondence type:</b>
  <%= link_to @correspondence.correspondence_type.name, @correspondence.correspondence_type %>
</p>

<p>
  <b>Representative:</b>
  <%= link_to "#{@correspondence.representative.first_name} #{@correspondence.representative.surname}", @correspondence.representative %>
</p>

<p>
  <b>Stakeholder:</b>
  <%= link_to @correspondence.stakeholder.organisation, @correspondence.stakeholder %>
</p>

<p>
  <b>Subject:</b>
  <%= @correspondence.subject %>
</p>

<p>
  <b>Comment:</b>
  <%= @correspondence.comment %>
</p>

<p>
  <b>Risk:</b>
  <%= link_to @correspondence.risk.name, @correspondence.risk %>
</p>


<%= link_to 'Edit', edit_correspondence_path(@correspondence) %> |
<%= link_to 'Back', correspondences_path %>